# Generated by Django 3.1.7 on 2021-05-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
